### ISSUE TITLE
Find out how long it takes to fetch 20 users data at once and api limit of Phabricator and Gerrit

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#110]
This is a microtask for issue #58 
assigning to @NdibeRaymond

**Comment by NdibeRaymond** [comment]
@srish I don't have the permission to assign this repository to myself

**Comment by NdibeRaymond** [comment]
@srish please if you wouldn't mind, I would love to know if there is an existing csv file created for testing purpose that contains names of contributors on both phabricator and garrit

**Comment by srish** [comment]
@NdibeRaymond You can save the info below in a .csv file for testing. You may change info, but the format will remain the same.
```
fullname,Phabricator,Gerrit
rammanoj,Rammanojpotla,rammanoj
Aklapper,Aklapper,Aklapper
vasanth,Gopavasanth,gopavasanth
Jay prakash,Jayprakash12345,Jayprakash12345
tony thomas,01tonythomas,01tonythomas
srishti,srishakatux,SrishtiSethi
```

**Comment by NdibeRaymond** [comment]
I made the mistake of posting my findings on the parent issue. So I'd be copying it over to this place now

**Comment by NdibeRaymond** [comment]
Since we are already making use of asyncio to fetch user commits asynchronously, I don't see a reason why we can't fetch the data of several users asynchronously too. Though the asyncio part of the codebase is a bit complicated, I think I am getting the hang of it. Currently experimenting on a way to achieve this. If it works, i think it will reduce total request time to by more than 80% or something close.
Any reason you think this wouldn't work @srish and @rammanoj  ?

**Update**
This has been implemented and tested to some extent. It didn't perform as much as I thought, though that might be because of poor internet connection. I will submit a non-mergeable PR so you can clone and give your feedback. In the meantime, I'd continue exploring other options

**Comment by NdibeRaymond** [comment]
**UPDATE**
I have been looking at the perceval tool and it looks like something that has all the potentials to solve all the major problems we are facing here. Is there a reason we can't use this @srish , @tuxology , @rammanoj ?
Currently I am trying to gather as much information as I can. Will try using perceval soon then give my report.
**Link**:(https://chaoss.github.io/grimoirelab-tutorial/perceval/intro.html)

**UPDATE**
perceval certainly has the potential, but it is impractical for now. I installed the required packages and fetched a couple of data from github API (requires similar step for gerrit and phabricator). The data being returned is too raw and broad to be of any immediate use. The data requires much more further processing. Seeing that bitergia makes use of perceval, I think it would take months to build something strong enough to make sense of the data.

**Comment by NdibeRaymond** [comment]
**UPDATE**
The fact that internet speed varies around the globe and that servers speed are on a different level entirely compared to private user's internet speed makes it a bit more difficult to answer the question of the time taken to fetch a single users data, and the time it would take to get user data for 20 - 30 users, since it all depends partly on the internet speed of the system making the API call.

To solve this, I modified WikiContrib (in ways that are un-mergeable). I will be submitting a PR soon with regards to that.
Anyone can clone it, upload CSV files and see how long it takes to fetch the whole data based on their internet speed, then come to their own conclusion.
I believe this is a better approach than given fixed numbers that are guaranteed to vary based on location.

**Comment by NdibeRaymond** [comment]
**Update**
It appears one major problem we are having is with API rate limits.
while testing the concurrent user data fetching I implemented ( Yet to push the research PR), I noticed that there are costs associated to making rapid API calls especially with Phabricator conduit API. For example, making three concurrent API requests to fetch information about three different users will take varying amount of time to return a response, maybe first request takes 4sec, next takes 8, and so on.

The obvious option to this problem is catching but the issue that arises is how to make sure the cache is up to date.
I was researching and found out that Phabricator has a webhook capability of some sort. This means Phabricator can notify you of changes to the remote data so you can update your cache accordingly.

Of course all this is still in idea form and I still have just surface knowledge of the Phabricator webhook feature, but this seems like a good thing.
I will keep you updated on my findings, @srish

**Comment by rammanoj** [comment]
@NdibeRaymond Caching does not solve the issue. It may solve one issue but it raises many other ones... I see your comments and are you sure that the API requests are truely failing ?

When I am developing this app, I made requests till upto 5 users. It is taking much time but I think there is no limit of how many requests you can make. Please correct me if I am wrong. It may take a while because in phabricator we can not make the API requests concurrently. In the case of a user, all the contributions are paginated and need to be made in sequential manner.

Can I also know how long are you fetching the data (i.e I mean the timestamp). If you can make the correct use of asycio, you can make all the requests of 20 users in parallel manner. Ofcourse sequential part can not be removed but it can be decreased.

Can you please post the code you wrote here so that It could be helpful for others ?

**Comment by NdibeRaymond** [comment]
I didn't say they are failing @rammanoj . I said that there is a kind of rate limit. What I mean by limit is this:
If we assume that retrieving a users data takes 2seconds, it will be fair to assume fetching 2 users data will take the same 2seconds if done concurrently, and fetching 20 users data will still take the same 2seconds since it is concurrent. But experiment proves otherwise. What I found is that the more you hit the endpoints, the more latency increases. So the first users data might take 2seconds, but the second will take 4seconds, and this is if you ran it concurrently. If you would love to see it yourself, it's all in PR #158 .

**Comment by srish** [comment]
@NdibeRaymond You may close this now if there isn't anything remaining to be done here.
